<a href="https://colab.research.google.com/github/salimNabbout/MFP/blob/main/dadosMyFitnessPall.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importação do pandas

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import missingno as ms # para tratamento de missings

# transformação Numerica
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

# transformação categórica
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

# Exibição de Dados no Jupyter Notebook

from IPython.display import display

In [2]:
MFP= pd.read_csv(r'/content/Resumo-da-alimentação-2014-12-28-a-2023-05-06.csv')

In [4]:
type(MFP)

pandas.core.frame.DataFrame

In [5]:
MFP.head()

,Data,Refeição,Tempo,Calorias,Gorduras (g),Gorduras saturadas,Gorduras poliinsaturadas,Gorduras monoinsaturadas,Gorduras trans,Colesterol,...,Potássio,Carboidratos (g),Fibra,Açucar,Proteínas (g),Vitamina A,Vitamina C,Cálcio,Ferro,export_headers.note
0,2019-06-02,Café da manhã,8:55 AM,340.0,25.5,9.9,0.0,0.0,0.0,0.0,...,0.0,1.5,0.0,0.0,26.5,0.0,0.0,0.0,0.0,NaN
1,2019-07-15,Café da manhã,NaN,480.0,37.2,0.0,0.0,0.0,0.0,1032.0,...,0.0,2.4,0.0,0.0,31.2,0.0,0.0,0.0,0.0,NaN
2,2019-07-15,Almoço,NaN,702.0,13.5,6.0,0.0,0.0,0.0,0.0,...,0.0,1.5,0.0,0.0,34.5,0.0,0.0,0.0,0.0,NaN
3,2020-09-06,Almoço,NaN,180.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,37.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,NaN
4,2020-11-02,Café da manhã,NaN,109.0,0.2,1.0,0.0,0.0,0.0,0.0,...,119.0,23.2,1.0,0.2,3.1,0.0,0.0,12.0,0.0,NaN

In [7]:
MFP.tail()

,Data,Refeição,Tempo,Calorias,Gorduras (g),Gorduras saturadas,Gorduras poliinsaturadas,Gorduras monoinsaturadas,Gorduras trans,Colesterol,...,Potássio,Carboidratos (g),Fibra,Açucar,Proteínas (g),Vitamina A,Vitamina C,Cálcio,Ferro,export_headers.note
1099,2023-01-06,Jantar,8:40 PM,128.3,0.2,0.2,0.0,0.0,0.0,0.0,...,14.7,28.1,1.6,0.0,2.5,0.0,0.0,0.4,0.6,NaN
1100,2023-01-06,Jantar,8:45 PM,96.5,0.6,0.1,0.2,0.1,0.0,0.0,...,662.0,22.7,6.0,0.0,4.2,134.0,122.0,0.5,5.5,NaN
1101,2023-01-07,Café da manhã,NaN,366.9,22.6,4.9,0.2,2.0,0.0,57.5,...,93.0,29.9,1.2,0.0,10.9,6.1,0.0,28.2,0.6,NaN
1102,2023-01-07,Almoço,NaN,615.6,38.4,15.2,0.0,0.0,0.4,113.2,...,0.0,28.4,0.0,0.0,42.4,0.0,0.0,0.0,0.0,NaN
1103,2023-02-21,Café da manhã,NaN,386.3,28.9,22.7,1.1,2.9,0.0,0.0,...,0.0,17.3,2.0,0.6,6.1,0.0,0.0,109.3,0.0,NaN

In [8]:
MFP.columns

Index(['Data', 'Refeição', 'Tempo', 'Calorias', 'Gorduras (g)',
       'Gorduras saturadas', 'Gorduras poliinsaturadas',
       'Gorduras monoinsaturadas', 'Gorduras trans', 'Colesterol',
       'Sódio (mg)', 'Potássio', 'Carboidratos (g)', 'Fibra', 'Açucar',
       'Proteínas (g)', 'Vitamina A', 'Vitamina C', 'Cálcio', 'Ferro',
       'export_headers.note'],
      dtype='object')

In [9]:
MFP.shape

(1104, 21)

In [10]:
MFP.count()

Data                        1104
Refeição                    1104
Tempo                        246
Calorias                    1104
Gorduras (g)                1104
Gorduras saturadas          1104
Gorduras poliinsaturadas    1104
Gorduras monoinsaturadas    1104
Gorduras trans              1104
Colesterol                  1104
Sódio (mg)                  1104
Potássio                    1104
Carboidratos (g)            1104
Fibra                       1104
Açucar                      1104
Proteínas (g)               1104
Vitamina A                  1104
Vitamina C                  1104
Cálcio                      1104
Ferro                       1104
export_headers.note            0
dtype: int64

In [11]:
MFP.describe()

,Calorias,Gorduras (g),Gorduras saturadas,Gorduras poliinsaturadas,Gorduras monoinsaturadas,Gorduras trans,Colesterol,Sódio (mg),Potássio,Carboidratos (g),Fibra,Açucar,Proteínas (g),Vitamina A,Vitamina C,Cálcio,Ferro,export_headers.note
count,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,1104.000000,0.0
mean,420.239493,17.173098,4.452083,0.968841,1.966576,0.151902,97.938406,385.563768,370.978986,33.384239,4.778804,2.096196,32.737319,22.427989,23.452355,13.888859,7.902899,NaN
std,262.586841,16.009921,6.521250,2.136152,4.349091,1.564403,195.957188,689.534442,427.201776,27.440714,5.044447,5.883894,35.166136,172.340024,67.113407,42.018196,17.878414,NaN
min,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,194.700000,5.000000,0.200000,0.000000,0.000000,0.000000,0.000000,23.975000,0.000000,13.825000,0.600000,0.000000,5.875000,0.000000,0.000000,0.000000,0.000000,NaN
50%,421.850000,13.950000,2.700000,0.100000,0.000000,0.000000,0.000000,144.300000,227.300000,29.300000,3.200000,0.000000,25.800000,0.000000,0.000000,2.600000,2.000000,NaN
75%,596.425000,25.000000,6.400000,0.700000,2.000000,0.000000,112.000000,450.125000,585.675000,45.025000,7.300000,0.825000,48.000000,2.400000,12.400000,10.825000,8.000000,NaN
max,1717.900000,201.600000,136.100000,20.200000,55.500000,22.500000,1668.000000,6663.000000,3750.000000,188.500000,27.600000,58.300000,336.600000,3643.500000,687.000000,710.200000,184.400000,NaN

In [15]:
URLMFP = (r'https://raw.githubusercontent.com/salimNabbout/MFP/main/Resumo-da-alimenta%C3%A7%C3%A3o-2014-12-28-a-2023-05-06.csv')

MYFP = pd.read_csv(URLMFP, delimiter=',')

MYFP.head()

,Data,Refeição,Tempo,Calorias,Gorduras (g),Gorduras saturadas,Gorduras poliinsaturadas,Gorduras monoinsaturadas,Gorduras trans,Colesterol,...,Potássio,Carboidratos (g),Fibra,Açucar,Proteínas (g),Vitamina A,Vitamina C,Cálcio,Ferro,export_headers.note
0,2019-06-02,Café da manhã,8:55 AM,340.0,25.5,9.9,0.0,0.0,0.0,0.0,...,0.0,1.5,0.0,0.0,26.5,0.0,0.0,0.0,0.0,NaN
1,2019-07-15,Café da manhã,NaN,480.0,37.2,0.0,0.0,0.0,0.0,1032.0,...,0.0,2.4,0.0,0.0,31.2,0.0,0.0,0.0,0.0,NaN
2,2019-07-15,Almoço,NaN,702.0,13.5,6.0,0.0,0.0,0.0,0.0,...,0.0,1.5,0.0,0.0,34.5,0.0,0.0,0.0,0.0,NaN
3,2020-09-06,Almoço,NaN,180.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,37.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,NaN
4,2020-11-02,Café da manhã,NaN,109.0,0.2,1.0,0.0,0.0,0.0,0.0,...,119.0,23.2,1.0,0.2,3.1,0.0,0.0,12.0,0.0,NaN

In [16]:
MYFP.isnull().sum()

Data                           0
Refeição                       0
Tempo                        858
Calorias                       0
Gorduras (g)                   0
Gorduras saturadas             0
Gorduras poliinsaturadas       0
Gorduras monoinsaturadas       0
Gorduras trans                 0
Colesterol                     0
Sódio (mg)                     0
Potássio                       0
Carboidratos (g)               0
Fibra                          0
Açucar                         0
Proteínas (g)                  0
Vitamina A                     0
Vitamina C                     0
Cálcio                         0
Ferro                          0
export_headers.note         1104
dtype: int64